// Reading passages for the voice screening, keyed by language.
// Each passage is a neutral paragraph the candidate reads aloud so we can assess
// fluency in the target language. Candidates read for ~30s+ and need not finish
// the whole passage. Languages without a curated passage fall back to a
// free-speech prompt in that language (see getReadingTask).

export const READING_PASSAGES: Record<string, string> = {
  English:
    'Thank you for taking the time to complete this short voice recording. Please read the following passage aloud clearly, at a calm and natural pace, just as you would speak with a customer or a colleague during a normal working day. There is no need to rush. What matters most is that your words are easy to understand and that you sound confident, friendly, and relaxed. Good communication is one of the most important skills in any role. It means speaking clearly, listening carefully to what the other person needs, and responding with patience and respect. When we communicate well, we help each person feel heard, valued, and understood, even when the situation is difficult or the answer is not the one they hoped to hear. A calm and friendly voice can turn a frustrating moment into a positive experience. Working as part of a remote team also requires focus, honesty, and reliability. We trust every member of our team to manage their time well, to be present and prepared for each shift, and to ask for help whenever they need it. Mistakes will happen from time to time, and that is completely normal. What truly counts is how we learn from them and keep improving together. As you read these words, imagine that you are already part of our team, speaking with someone who is depending on you for support. Take a breath, relax your shoulders, and let your natural voice come through. We genuinely appreciate the effort you are making today, and we look forward to learning more about you, your experience, and the strengths you would bring to our growing team. Thank you again, and good luck.',
  Spanish:
    'Gracias por tomarse el tiempo para completar esta breve grabación de voz. Por favor, lea el siguiente texto en voz alta con claridad, a un ritmo tranquilo y natural, tal como hablaría con un cliente o un compañero durante un día normal de trabajo. No hay necesidad de apresurarse. Lo más importante es que sus palabras sean fáciles de entender y que suene seguro, amable y relajado. La buena comunicación es una de las habilidades más importantes en cualquier puesto. Significa hablar con claridad, escuchar con atención lo que la otra persona necesita y responder con paciencia y respeto. Cuando nos comunicamos bien, ayudamos a que cada persona se sienta escuchada, valorada y comprendida, incluso cuando la situación es difícil o la respuesta no es la que esperaba. Una voz tranquila y amable puede convertir un momento de frustración en una experiencia positiva. Trabajar como parte de un equipo remoto también requiere concentración, honestidad y responsabilidad. Confiamos en que cada miembro de nuestro equipo administre bien su tiempo, esté presente y preparado para cada turno, y pida ayuda cuando la necesite. De vez en cuando se cometen errores, y eso es completamente normal. Lo que realmente importa es cómo aprendemos de ellos y seguimos mejorando juntos. Mientras lee estas palabras, imagine que ya forma parte de nuestro equipo, hablando con alguien que depende de usted para recibir apoyo. Respire, relaje los hombros y deje salir su voz natural. Apreciamos sinceramente el esfuerzo que está haciendo hoy, y esperamos conocer más sobre usted, su experiencia y las fortalezas que aportaría a nuestro equipo en crecimiento. Gracias de nuevo y mucha suerte.',
  French:
    "Merci d'avoir pris le temps de réaliser ce court enregistrement vocal. Veuillez lire le texte suivant à voix haute, clairement, à un rythme calme et naturel, comme vous parleriez à un client ou à un collègue au cours d'une journée de travail ordinaire. Il n'est pas nécessaire de vous précipiter. Ce qui compte le plus, c'est que vos mots soient faciles à comprendre et que vous paraissiez confiant, aimable et détendu. Une bonne communication est l'une des compétences les plus importantes dans tout poste. Cela signifie parler clairement, écouter attentivement ce dont l'autre personne a besoin et répondre avec patience et respect. Lorsque nous communiquons bien, nous aidons chaque personne à se sentir entendue, valorisée et comprise, même lorsque la situation est difficile ou que la réponse n'est pas celle qu'elle espérait. Une voix calme et chaleureuse peut transformer un moment frustrant en une expérience positive. Travailler au sein d'une équipe à distance exige aussi de la concentration, de l'honnêteté et de la fiabilité. Nous faisons confiance à chaque membre de notre équipe pour bien gérer son temps, être présent et préparé à chaque service, et demander de l'aide chaque fois qu'il en a besoin. Des erreurs se produiront de temps en temps, et c'est tout à fait normal. Ce qui compte vraiment, c'est la façon dont nous en tirons des leçons et continuons à nous améliorer ensemble. En lisant ces mots, imaginez que vous faites déjà partie de notre équipe, en train de parler à quelqu'un qui compte sur votre soutien. Respirez, détendez vos épaules et laissez votre voix naturelle s'exprimer. Nous apprécions sincèrement l'effort que vous faites aujourd'hui et nous avons hâte d'en apprendre davantage sur vous. Merci encore et bonne chance.",
  'French US Based':
    "Merci d'avoir pris le temps de réaliser ce court enregistrement vocal. Veuillez lire le texte suivant à voix haute, clairement, à un rythme calme et naturel, comme vous parleriez à un client ou à un collègue au cours d'une journée de travail ordinaire. Il n'est pas nécessaire de vous précipiter. Ce qui compte le plus, c'est que vos mots soient faciles à comprendre et que vous paraissiez confiant, aimable et détendu. Une bonne communication est l'une des compétences les plus importantes dans tout poste. Cela signifie parler clairement, écouter attentivement ce dont l'autre personne a besoin et répondre avec patience et respect. Lorsque nous communiquons bien, nous aidons chaque personne à se sentir entendue, valorisée et comprise, même lorsque la situation est difficile ou que la réponse n'est pas celle qu'elle espérait. Une voix calme et chaleureuse peut transformer un moment frustrant en une expérience positive. Travailler au sein d'une équipe à distance exige aussi de la concentration, de l'honnêteté et de la fiabilité. Nous faisons confiance à chaque membre de notre équipe pour bien gérer son temps, être présent et préparé à chaque service, et demander de l'aide chaque fois qu'il en a besoin. Des erreurs se produiront de temps en temps, et c'est tout à fait normal. Ce qui compte vraiment, c'est la façon dont nous en tirons des leçons et continuons à nous améliorer ensemble. En lisant ces mots, imaginez que vous faites déjà partie de notre équipe, en train de parler à quelqu'un qui compte sur votre soutien. Respirez, détendez vos épaules et laissez votre voix naturelle s'exprimer. Nous apprécions sincèrement l'effort que vous faites aujourd'hui et nous avons hâte d'en apprendre davantage sur vous. Merci encore et bonne chance.",
  Portuguese:
    'Obrigado por dedicar o seu tempo para concluir esta breve gravação de voz. Por favor, leia o texto a seguir em voz alta, com clareza, num ritmo calmo e natural, tal como falaria com um cliente ou um colega durante um dia normal de trabalho. Não há necessidade de pressa. O mais importante é que as suas palavras sejam fáceis de entender e que soe confiante, simpático e tranquilo. A boa comunicação é uma das competências mais importantes em qualquer função. Significa falar com clareza, ouvir com atenção aquilo de que a outra pessoa precisa e responder com paciência e respeito. Quando comunicamos bem, ajudamos cada pessoa a sentir-se ouvida, valorizada e compreendida, mesmo quando a situação é difícil ou a resposta não é a que esperava. Uma voz calma e amável pode transformar um momento de frustração numa experiência positiva. Trabalhar como parte de uma equipa remota também exige concentração, honestidade e responsabilidade. Confiamos que cada membro da nossa equipa faça uma boa gestão do seu tempo, esteja presente e preparado para cada turno e peça ajuda sempre que precisar. Erros acontecem de vez em quando, e isso é completamente normal. O que realmente importa é como aprendemos com eles e continuamos a melhorar juntos. Enquanto lê estas palavras, imagine que já faz parte da nossa equipa, a falar com alguém que depende do seu apoio. Respire, relaxe os ombros e deixe a sua voz natural fluir. Agradecemos sinceramente o esforço que está a fazer hoje e estamos ansiosos por saber mais sobre si, a sua experiência e as qualidades que traria à nossa equipa em crescimento. Obrigado mais uma vez e boa sorte.',
  Italian:
    "Grazie per aver dedicato del tempo a completare questa breve registrazione vocale. Per favore, leggi il seguente brano ad alta voce, in modo chiaro, con un ritmo calmo e naturale, proprio come parleresti con un cliente o un collega durante una normale giornata di lavoro. Non c'è bisogno di affrettarsi. Ciò che conta di più è che le tue parole siano facili da capire e che tu suoni sicuro, cordiale e rilassato. Una buona comunicazione è una delle competenze più importanti in qualsiasi ruolo. Significa parlare chiaramente, ascoltare con attenzione ciò di cui l'altra persona ha bisogno e rispondere con pazienza e rispetto. Quando comunichiamo bene, aiutiamo ogni persona a sentirsi ascoltata, apprezzata e compresa, anche quando la situazione è difficile o la risposta non è quella che sperava. Una voce calma e gentile può trasformare un momento di frustrazione in un'esperienza positiva. Lavorare come parte di un team da remoto richiede anche concentrazione, onestà e affidabilità. Ci fidiamo che ogni membro del nostro team gestisca bene il proprio tempo, sia presente e preparato per ogni turno e chieda aiuto ogni volta che ne ha bisogno. Gli errori capitano di tanto in tanto, ed è del tutto normale. Ciò che conta davvero è come impariamo da essi e continuiamo a migliorare insieme. Mentre leggi queste parole, immagina di far già parte del nostro team, mentre parli con qualcuno che conta sul tuo supporto. Fai un respiro, rilassa le spalle e lascia emergere la tua voce naturale. Apprezziamo sinceramente lo sforzo che stai facendo oggi e non vediamo l'ora di saperne di più su di te. Grazie ancora e buona fortuna.",
  German:
    'Vielen Dank, dass Sie sich die Zeit nehmen, diese kurze Sprachaufnahme zu machen. Bitte lesen Sie den folgenden Text laut und deutlich vor, in einem ruhigen und natürlichen Tempo, so wie Sie an einem normalen Arbeitstag mit einem Kunden oder einer Kollegin sprechen würden. Es besteht kein Grund zur Eile. Am wichtigsten ist, dass Ihre Worte leicht zu verstehen sind und dass Sie selbstbewusst, freundlich und entspannt klingen. Gute Kommunikation ist eine der wichtigsten Fähigkeiten in jeder Rolle. Sie bedeutet, klar zu sprechen, aufmerksam zuzuhören, was die andere Person braucht, und mit Geduld und Respekt zu antworten. Wenn wir gut kommunizieren, helfen wir jeder Person, sich gehört, geschätzt und verstanden zu fühlen, selbst wenn die Situation schwierig ist oder die Antwort nicht die erhoffte ist. Eine ruhige und freundliche Stimme kann einen frustrierenden Moment in eine positive Erfahrung verwandeln. Die Arbeit in einem Remote-Team erfordert außerdem Konzentration, Ehrlichkeit und Zuverlässigkeit. Wir vertrauen darauf, dass jedes Teammitglied seine Zeit gut einteilt, für jede Schicht anwesend und vorbereitet ist und um Hilfe bittet, wann immer es nötig ist. Fehler passieren von Zeit zu Zeit, und das ist völlig normal. Was wirklich zählt, ist, wie wir aus ihnen lernen und uns gemeinsam weiter verbessern. Während Sie diese Worte lesen, stellen Sie sich vor, dass Sie bereits Teil unseres Teams sind und mit jemandem sprechen, der auf Ihre Unterstützung angewiesen ist. Atmen Sie durch, entspannen Sie Ihre Schultern und lassen Sie Ihre natürliche Stimme erklingen. Wir schätzen Ihren heutigen Einsatz aufrichtig und freuen uns darauf, mehr über Sie zu erfahren. Nochmals vielen Dank und viel Erfolg.',
  Arabic:
    'شكرًا لك على تخصيص بعض الوقت لإكمال هذا التسجيل الصوتي القصير. يُرجى قراءة النص التالي بصوت عالٍ وبوضوح، وبوتيرة هادئة وطبيعية، تمامًا كما تتحدث مع عميل أو زميل خلال يوم عمل عادي. لا داعي للعجلة. أهم ما في الأمر أن تكون كلماتك سهلة الفهم وأن يبدو صوتك واثقًا وودودًا ومسترخيًا. يُعد التواصل الجيد من أهم المهارات في أي وظيفة. فهو يعني التحدث بوضوح، والإنصات بعناية لما يحتاجه الطرف الآخر، والرد بصبر واحترام. عندما نتواصل جيدًا، نساعد كل شخص على الشعور بأنه مسموع ومقدَّر ومفهوم، حتى عندما يكون الموقف صعبًا أو لا تكون الإجابة كما يأمل. الصوت الهادئ والودود قادر على تحويل لحظة محبطة إلى تجربة إيجابية. كما يتطلب العمل ضمن فريق عن بُعد التركيز والصدق والموثوقية. نحن نثق بأن كل عضو في فريقنا يحسن إدارة وقته، ويكون حاضرًا ومستعدًا لكل وردية، ويطلب المساعدة كلما احتاج إليها. ستحدث الأخطاء من حين لآخر، وهذا أمر طبيعي تمامًا. وما يهم حقًا هو كيف نتعلم منها ونستمر في التحسن معًا. وبينما تقرأ هذه الكلمات، تخيّل أنك بالفعل جزء من فريقنا، تتحدث مع شخص يعتمد عليك في الدعم. خذ نفسًا عميقًا، وأرخِ كتفيك، ودع صوتك الطبيعي ينساب. نحن نقدّر بصدق الجهد الذي تبذله اليوم، ونتطلع إلى معرفة المزيد عنك وعن خبرتك ونقاط قوتك التي ستضيفها إلى فريقنا المتنامي. شكرًا لك مرة أخرى، ونتمنى لك التوفيق.',
  Urdu:
    'یہ مختصر صوتی ریکارڈنگ مکمل کرنے کے لیے وقت نکالنے پر آپ کا شکریہ۔ براہِ کرم درج ذیل عبارت کو بلند آواز میں، واضح انداز میں، اور ایک پُرسکون اور فطری رفتار کے ساتھ پڑھیں، بالکل ویسے ہی جیسے آپ کسی عام کاروباری دن میں کسی گاہک یا ساتھی سے بات کرتے ہیں۔ جلدی کرنے کی کوئی ضرورت نہیں۔ سب سے اہم بات یہ ہے کہ آپ کے الفاظ سمجھنے میں آسان ہوں اور آپ کی آواز پُراعتماد، خوش اخلاق اور پُرسکون محسوس ہو۔ اچھی بات چیت کسی بھی کردار کی سب سے اہم مہارتوں میں سے ایک ہے۔ اس کا مطلب ہے واضح انداز میں بولنا، دوسرے شخص کی ضرورت کو غور سے سننا، اور صبر اور احترام کے ساتھ جواب دینا۔ جب ہم اچھی طرح بات چیت کرتے ہیں تو ہم ہر فرد کو یہ احساس دلاتے ہیں کہ اس کی بات سنی گئی، اس کی قدر کی گئی اور اسے سمجھا گیا، چاہے صورتحال مشکل ہو یا جواب وہ نہ ہو جس کی اسے امید تھی۔ ایک پُرسکون اور دوستانہ آواز کسی مایوس کن لمحے کو ایک مثبت تجربے میں بدل سکتی ہے۔ ریموٹ ٹیم کے حصے کے طور پر کام کرنے کے لیے توجہ، ایمانداری اور قابلِ اعتماد ہونا بھی ضروری ہے۔ ہمیں اپنی ٹیم کے ہر رکن پر بھروسہ ہے کہ وہ اپنے وقت کا اچھا انتظام کرے گا، ہر شفٹ کے لیے حاضر اور تیار رہے گا، اور جب بھی ضرورت ہو مدد طلب کرے گا۔ غلطیاں کبھی کبھار ہوتی رہتی ہیں، اور یہ بالکل فطری بات ہے۔ اصل اہمیت اس بات کی ہے کہ ہم ان سے کیسے سیکھتے ہیں اور مل کر بہتر ہوتے رہتے ہیں۔ ان الفاظ کو پڑھتے ہوئے تصور کریں کہ آپ پہلے سے ہی ہماری ٹیم کا حصہ ہیں۔ گہری سانس لیں، کندھے ڈھیلے چھوڑیں، اور اپنی فطری آواز کو ابھرنے دیں۔ ہم آج آپ کی کوشش کو دل سے سراہتے ہیں اور آپ کے بارے میں مزید جاننے کے منتظر ہیں۔ ایک بار پھر شکریہ اور نیک خواہشات۔',
  Hindi:
    'इस छोटी सी आवाज़ रिकॉर्डिंग को पूरा करने के लिए समय निकालने हेतु आपका धन्यवाद। कृपया नीचे दिए गए अनुच्छेद को ऊँची आवाज़ में, स्पष्ट रूप से और एक शांत एवं स्वाभाविक गति से पढ़ें, ठीक वैसे ही जैसे आप किसी सामान्य कार्यदिवस में किसी ग्राहक या सहकर्मी से बात करते हैं। जल्दबाज़ी करने की कोई आवश्यकता नहीं है। सबसे महत्वपूर्ण बात यह है कि आपके शब्द समझने में आसान हों और आपकी आवाज़ आत्मविश्वासी, मित्रवत और सहज लगे। अच्छा संवाद किसी भी भूमिका में सबसे महत्वपूर्ण कौशलों में से एक है। इसका अर्थ है स्पष्ट रूप से बोलना, सामने वाले व्यक्ति की ज़रूरत को ध्यान से सुनना, और धैर्य तथा सम्मान के साथ उत्तर देना। जब हम अच्छी तरह संवाद करते हैं, तो हम हर व्यक्ति को यह अनुभव कराते हैं कि उसकी बात सुनी गई, उसकी क़द्र की गई और उसे समझा गया, भले ही परिस्थिति कठिन हो या उत्तर वह न हो जिसकी उसे आशा थी। एक शांत और मधुर आवाज़ किसी निराशाजनक क्षण को एक सकारात्मक अनुभव में बदल सकती है। किसी रिमोट टीम के हिस्से के रूप में काम करने के लिए एकाग्रता, ईमानदारी और विश्वसनीयता भी आवश्यक है। हमें अपनी टीम के हर सदस्य पर भरोसा है कि वह अपने समय का अच्छा प्रबंधन करेगा, हर शिफ्ट के लिए उपस्थित और तैयार रहेगा, और जब भी आवश्यकता हो मदद माँगेगा। गलतियाँ समय-समय पर होती रहती हैं, और यह पूरी तरह सामान्य है। असल में मायने यह रखता है कि हम उनसे कैसे सीखते हैं और मिलकर बेहतर होते रहते हैं। इन शब्दों को पढ़ते समय कल्पना कीजिए कि आप पहले से ही हमारी टीम का हिस्सा हैं। एक गहरी साँस लें, अपने कंधों को ढीला छोड़ें, और अपनी स्वाभाविक आवाज़ को बाहर आने दें। हम आज आपके प्रयास की सच्ची सराहना करते हैं और आपके बारे में अधिक जानने के लिए उत्सुक हैं। एक बार फिर धन्यवाद और शुभकामनाएँ।',
  Russian:
    'Спасибо, что нашли время сделать эту короткую голосовую запись. Пожалуйста, прочитайте следующий отрывок вслух, чётко, в спокойном и естественном темпе, так же, как вы говорили бы с клиентом или коллегой в обычный рабочий день. Спешить не нужно. Самое главное — чтобы ваши слова были понятны, а голос звучал уверенно, доброжелательно и спокойно. Хорошее общение — один из самых важных навыков в любой роли. Оно означает говорить ясно, внимательно слушать то, что нужно собеседнику, и отвечать терпеливо и уважительно. Когда мы общаемся хорошо, мы помогаем каждому человеку почувствовать, что его услышали, оценили и поняли, даже если ситуация сложная или ответ не тот, на который он надеялся. Спокойный и доброжелательный голос способен превратить неприятный момент в положительный опыт. Работа в удалённой команде также требует сосредоточенности, честности и надёжности. Мы доверяем каждому участнику нашей команды грамотно распоряжаться своим временем, быть на месте и готовым к каждой смене, а также просить о помощи, когда это необходимо. Ошибки время от времени случаются, и это совершенно нормально. По-настоящему важно то, как мы извлекаем из них уроки и продолжаем совершенствоваться вместе. Читая эти слова, представьте, что вы уже часть нашей команды и говорите с человеком, который рассчитывает на вашу поддержку. Сделайте вдох, расслабьте плечи и позвольте звучать своему естественному голосу. Мы искренне ценим усилия, которые вы прилагаете сегодня, и с нетерпением ждём возможности узнать больше о вас, вашем опыте и сильных сторонах, которые вы привнесёте в нашу растущую команду. Ещё раз спасибо и удачи.',
  Mandarin:
    '感谢您抽出时间完成这段简短的语音录制。请清晰地、以平静而自然的语速大声朗读以下段落，就像您在平常的工作日里与客户或同事交谈一样。不必着急，最重要的是让您的话语容易理解，并且听起来自信、友好而放松。良好的沟通是任何岗位中最重要的技能之一。它意味着把话说清楚，认真倾听对方的需求，并以耐心和尊重作出回应。当我们沟通顺畅时，就能让每个人都感到被倾听、被重视、被理解，即使情况很棘手，或者答案并不是他们所期望的。平静而友善的声音可以把令人沮丧的时刻转变为积极的体验。作为远程团队的一员工作，同样需要专注、诚实和可靠。我们相信团队中的每一位成员都能妥善安排时间，按时出勤并为每一个班次做好准备，并在需要时主动寻求帮助。错误偶尔会发生，这完全正常。真正重要的是我们如何从中吸取教训，并继续共同进步。在朗读这些文字时，请想象您已经是我们团队的一员，正在与一位依赖您提供支持的人交谈。深吸一口气，放松双肩，让您自然的声音流露出来。我们由衷地感谢您今天所付出的努力，也期待更多地了解您、您的经验，以及您能为我们不断成长的团队带来的优势。再次感谢您，祝您好运。',
  Cantonese:
    '多謝你抽時間完成呢段簡短嘅語音錄音。請你清晰咁、用平靜而自然嘅語速大聲朗讀以下段落，就好似你喺平常嘅返工日同客人或者同事傾偈一樣。唔使心急，最緊要係你嘅說話容易明白，聽落自信、友善又輕鬆。良好嘅溝通係任何崗位入面最重要嘅技能之一。佢意味住講嘢清楚，用心聆聽對方嘅需要，並且以耐心同尊重去回應。當我哋溝通得好，就可以令每個人都覺得被聆聽、被重視同被理解，即使情況困難，或者答案唔係佢哋所期望嘅。一把平靜又親切嘅聲音，可以將一個令人沮喪嘅時刻變成一次正面嘅體驗。作為遠程團隊嘅一員，同樣需要專注、誠實同可靠。我哋相信團隊入面每一位成員都識得好好安排時間，準時出席並為每一更做好準備，喺有需要嘅時候主動求助。錯誤偶爾會發生，呢樣係完全正常嘅。真正重要嘅係我哋點樣從中學習，並繼續一齊進步。當你朗讀呢啲文字嘅時候，請想像你已經係我哋團隊嘅一員，正喺度同一位依賴你支援嘅人傾偈。深呼吸一下，放鬆膊頭，讓你自然嘅聲音流露出嚟。我哋由衷感激你今日所付出嘅努力，亦期待更深入咁認識你。再次多謝，祝你好運。',
  Turkish:
    'Bu kısa sesli kaydı tamamlamak için zaman ayırdığınız için teşekkür ederiz. Lütfen aşağıdaki metni yüksek sesle, anlaşılır bir şekilde ve sakin, doğal bir tempoyla okuyun; tıpkı sıradan bir iş gününde bir müşteri ya da meslektaşınızla konuşur gibi. Acele etmenize gerek yok. En önemlisi, sözlerinizin kolay anlaşılır olması ve sesinizin kendinden emin, samimi ve rahat çıkmasıdır. İyi iletişim, her rolde en önemli becerilerden biridir. Açık konuşmak, karşınızdaki kişinin neye ihtiyacı olduğunu dikkatle dinlemek ve sabır ve saygıyla yanıt vermek anlamına gelir. İyi iletişim kurduğumuzda, durum zor olsa ya da yanıt umduğu gibi olmasa bile, her insanın duyulduğunu, değer gördüğünü ve anlaşıldığını hissetmesine yardımcı oluruz. Sakin ve güler yüzlü bir ses, sinir bozucu bir anı olumlu bir deneyime dönüştürebilir. Uzaktan bir ekibin parçası olarak çalışmak ayrıca odaklanma, dürüstlük ve güvenilirlik gerektirir. Ekibimizin her üyesinin zamanını iyi yöneteceğine, her vardiyaya hazır ve hazır bulunacağına ve ihtiyaç duyduğunda yardım isteyeceğine güveniyoruz. Zaman zaman hatalar olur ve bu tamamen normaldir. Asıl önemli olan, bunlardan nasıl ders çıkardığımız ve birlikte gelişmeye devam ettiğimizdir. Bu sözleri okurken, zaten ekibimizin bir parçası olduğunuzu ve desteğinize güvenen biriyle konuştuğunuzu hayal edin. Bir nefes alın, omuzlarınızı gevşetin ve doğal sesinizin ortaya çıkmasına izin verin. Bugün gösterdiğiniz çabayı içtenlikle takdir ediyor ve sizi, deneyiminizi ve büyüyen ekibimize katacağınız güçlü yönleri daha yakından tanımayı dört gözle bekliyoruz. Tekrar teşekkür eder, başarılar dileriz.',
  Indonesian:
    'Terima kasih telah meluangkan waktu untuk menyelesaikan rekaman suara singkat ini. Mohon bacakan paragraf berikut dengan lantang, jelas, dan dengan kecepatan yang tenang dan wajar, seperti saat Anda berbicara dengan pelanggan atau rekan kerja pada hari kerja biasa. Tidak perlu terburu-buru. Yang paling penting adalah kata-kata Anda mudah dipahami dan suara Anda terdengar percaya diri, ramah, dan santai. Komunikasi yang baik adalah salah satu keterampilan terpenting dalam peran apa pun. Itu berarti berbicara dengan jelas, mendengarkan dengan saksama apa yang dibutuhkan orang lain, dan menanggapi dengan sabar dan hormat. Ketika kita berkomunikasi dengan baik, kita membantu setiap orang merasa didengar, dihargai, dan dipahami, bahkan ketika situasinya sulit atau jawabannya bukan yang mereka harapkan. Suara yang tenang dan ramah dapat mengubah momen yang membuat frustrasi menjadi pengalaman yang positif. Bekerja sebagai bagian dari tim jarak jauh juga membutuhkan fokus, kejujuran, dan keandalan. Kami percaya setiap anggota tim kami mengelola waktunya dengan baik, hadir dan siap untuk setiap shift, serta meminta bantuan kapan pun diperlukan. Kesalahan akan terjadi dari waktu ke waktu, dan itu sepenuhnya wajar. Yang benar-benar penting adalah bagaimana kita belajar darinya dan terus berkembang bersama. Saat Anda membaca kata-kata ini, bayangkan bahwa Anda sudah menjadi bagian dari tim kami, berbicara dengan seseorang yang bergantung pada dukungan Anda. Tarik napas, rilekskan bahu Anda, dan biarkan suara alami Anda muncul. Kami sungguh menghargai usaha yang Anda lakukan hari ini, dan kami menantikan untuk mengenal Anda lebih jauh. Sekali lagi terima kasih, dan semoga sukses.',
  Vietnamese:
    'Cảm ơn bạn đã dành thời gian hoàn thành bản ghi âm ngắn này. Vui lòng đọc to đoạn văn sau một cách rõ ràng, với tốc độ bình tĩnh và tự nhiên, giống như khi bạn nói chuyện với một khách hàng hoặc đồng nghiệp trong một ngày làm việc bình thường. Không cần phải vội vàng. Điều quan trọng nhất là lời nói của bạn dễ hiểu và giọng nói của bạn nghe tự tin, thân thiện và thoải mái. Giao tiếp tốt là một trong những kỹ năng quan trọng nhất ở bất kỳ vị trí nào. Điều đó có nghĩa là nói rõ ràng, lắng nghe cẩn thận điều người khác cần, và phản hồi bằng sự kiên nhẫn và tôn trọng. Khi chúng ta giao tiếp tốt, chúng ta giúp mỗi người cảm thấy được lắng nghe, được coi trọng và được thấu hiểu, ngay cả khi tình huống khó khăn hoặc câu trả lời không như họ mong đợi. Một giọng nói bình tĩnh và thân thiện có thể biến một khoảnh khắc bực bội thành một trải nghiệm tích cực. Làm việc như một phần của nhóm từ xa cũng đòi hỏi sự tập trung, trung thực và đáng tin cậy. Chúng tôi tin tưởng mỗi thành viên trong nhóm quản lý thời gian tốt, có mặt và sẵn sàng cho mỗi ca làm việc, và yêu cầu giúp đỡ bất cứ khi nào cần. Sai lầm sẽ thỉnh thoảng xảy ra, và điều đó hoàn toàn bình thường. Điều thực sự quan trọng là cách chúng ta học hỏi từ chúng và cùng nhau tiến bộ. Khi đọc những dòng này, hãy hình dung rằng bạn đã là một phần của nhóm chúng tôi. Hãy hít thở, thả lỏng vai, và để giọng nói tự nhiên của bạn cất lên. Chúng tôi thực sự trân trọng nỗ lực của bạn hôm nay và mong được tìm hiểu thêm về bạn. Cảm ơn bạn một lần nữa và chúc may mắn.',
  Tagalog:
    'Salamat sa paglalaan ng oras upang kumpletuhin ang maikling voice recording na ito. Pakibasa nang malakas ang sumusunod na talata nang malinaw, sa kalmado at natural na bilis, tulad ng pakikipag-usap mo sa isang kustomer o katrabaho sa isang ordinaryong araw ng trabaho. Hindi mo kailangang magmadali. Ang pinakamahalaga ay madaling maunawaan ang iyong mga salita at tunog kang tiwala, magiliw, at relaks. Ang mahusay na komunikasyon ay isa sa pinakamahalagang kasanayan sa anumang tungkulin. Ibig sabihin nito ay magsalita nang malinaw, makinig nang mabuti sa pangangailangan ng ibang tao, at tumugon nang may pasensya at paggalang. Kapag mahusay tayong nakikipag-usap, natutulungan natin ang bawat tao na maramdamang naririnig, pinahahalagahan, at nauunawaan, kahit na mahirap ang sitwasyon o hindi iyon ang sagot na inaasahan nila. Ang isang kalmado at magiliw na tinig ay maaaring gawing positibong karanasan ang isang nakakabwisit na sandali. Ang pagtatrabaho bilang bahagi ng isang remote na koponan ay nangangailangan din ng pokus, katapatan, at pagiging maaasahan. Pinagkakatiwalaan namin ang bawat miyembro ng aming koponan na pamahalaan nang mabuti ang kanyang oras, naroroon at handa sa bawat shift, at humingi ng tulong kapag kinakailangan. Magkakamali tayo paminsan-minsan, at iyon ay normal lamang. Ang tunay na mahalaga ay kung paano tayo natututo mula rito at patuloy na umuunlad nang magkasama. Habang binabasa mo ang mga salitang ito, isipin na bahagi ka na ng aming koponan, na nakikipag-usap sa isang taong umaasa sa iyong suporta. Huminga, i-relaks ang iyong balikat, at hayaang lumabas ang iyong natural na boses. Tunay naming pinahahalagahan ang iyong pagsisikap ngayon, at inaasam naming makilala ka pa nang lubos. Maraming salamat muli, at good luck.',
  Bengali:
    'এই সংক্ষিপ্ত ভয়েস রেকর্ডিংটি সম্পূর্ণ করার জন্য সময় দেওয়ায় আপনাকে ধন্যবাদ। অনুগ্রহ করে নিচের অনুচ্ছেদটি স্পষ্টভাবে, একটি শান্ত ও স্বাভাবিক গতিতে জোরে পড়ুন, ঠিক যেভাবে আপনি একটি সাধারণ কর্মদিবসে কোনো গ্রাহক বা সহকর্মীর সঙ্গে কথা বলেন। তাড়াহুড়ো করার দরকার নেই। সবচেয়ে গুরুত্বপূর্ণ বিষয় হলো আপনার কথাগুলো সহজে বোঝা যায় এবং আপনার কণ্ঠস্বর আত্মবিশ্বাসী, বন্ধুত্বপূর্ণ ও স্বচ্ছন্দ শোনায়। ভালো যোগাযোগ যেকোনো ভূমিকায় সবচেয়ে গুরুত্বপূর্ণ দক্ষতাগুলোর একটি। এর অর্থ স্পষ্টভাবে কথা বলা, অপর ব্যক্তির প্রয়োজন মনোযোগ দিয়ে শোনা এবং ধৈর্য ও সম্মানের সঙ্গে সাড়া দেওয়া। যখন আমরা ভালোভাবে যোগাযোগ করি, তখন আমরা প্রত্যেক ব্যক্তিকে এই অনুভূতি দিই যে তার কথা শোনা হয়েছে, তাকে মূল্য দেওয়া হয়েছে এবং তাকে বোঝা হয়েছে, এমনকি পরিস্থিতি কঠিন হলেও বা উত্তরটি তার প্রত্যাশিত না হলেও। একটি শান্ত ও বন্ধুত্বপূর্ণ কণ্ঠস্বর একটি হতাশাজনক মুহূর্তকে একটি ইতিবাচক অভিজ্ঞতায় পরিণত করতে পারে। একটি দূরবর্তী দলের অংশ হিসেবে কাজ করার জন্য মনোযোগ, সততা এবং নির্ভরযোগ্যতাও প্রয়োজন। আমরা আমাদের দলের প্রত্যেক সদস্যের ওপর আস্থা রাখি যে তিনি তার সময় ভালোভাবে পরিচালনা করবেন, প্রতিটি শিফটের জন্য উপস্থিত ও প্রস্তুত থাকবেন এবং যখনই প্রয়োজন হবে সাহায্য চাইবেন। মাঝে মাঝে ভুল হবে, এবং তা সম্পূর্ণ স্বাভাবিক। সত্যিকারের গুরুত্বপূর্ণ বিষয় হলো আমরা সেগুলো থেকে কীভাবে শিখি এবং একসঙ্গে উন্নতি করতে থাকি। এই শব্দগুলো পড়ার সময় কল্পনা করুন যে আপনি ইতিমধ্যেই আমাদের দলের অংশ। একটি গভীর শ্বাস নিন, কাঁধ শিথিল করুন এবং আপনার স্বাভাবিক কণ্ঠস্বরকে বেরিয়ে আসতে দিন। আজ আপনার প্রচেষ্টাকে আমরা আন্তরিকভাবে মূল্য দিই এবং আপনার সম্পর্কে আরও জানতে আগ্রহী। আবারও ধন্যবাদ এবং শুভকামনা।',
  Korean:
    '이 짧은 음성 녹음을 완료하기 위해 시간을 내주셔서 감사합니다. 다음 글을 또렷하게, 차분하고 자연스러운 속도로 소리 내어 읽어 주세요. 평범한 근무일에 고객이나 동료와 이야기하듯이 읽으시면 됩니다. 서두를 필요는 없습니다. 가장 중요한 것은 당신의 말이 이해하기 쉽고, 목소리가 자신감 있고 친근하며 편안하게 들리는 것입니다. 좋은 의사소통은 어떤 역할에서든 가장 중요한 능력 중 하나입니다. 그것은 분명하게 말하고, 상대방이 무엇을 필요로 하는지 주의 깊게 듣고, 인내심과 존중을 담아 응답하는 것을 의미합니다. 우리가 잘 소통할 때, 상황이 어렵거나 원하던 답이 아니더라도 모든 사람이 자신의 말이 들리고, 존중받고, 이해받는다고 느끼도록 도울 수 있습니다. 차분하고 친절한 목소리는 답답한 순간을 긍정적인 경험으로 바꿀 수 있습니다. 원격 팀의 일원으로 일하는 것은 집중력, 정직함, 그리고 신뢰성도 요구합니다. 우리는 팀의 모든 구성원이 시간을 잘 관리하고, 각 근무에 준비된 상태로 참석하며, 필요할 때 언제든 도움을 요청할 것이라고 믿습니다. 실수는 때때로 일어나며, 그것은 지극히 정상적인 일입니다. 정말 중요한 것은 우리가 그것에서 무엇을 배우고 함께 계속 발전해 나가는가입니다. 이 글을 읽는 동안, 당신이 이미 우리 팀의 일원이 되어 당신의 도움을 필요로 하는 누군가와 이야기하고 있다고 상상해 보세요. 숨을 한 번 들이쉬고, 어깨의 긴장을 풀고, 당신의 자연스러운 목소리가 나오도록 하세요. 오늘 기울여 주신 노력에 진심으로 감사드리며, 당신과 당신의 경험에 대해 더 알아가기를 기대합니다. 다시 한번 감사드리며, 행운을 빕니다.',
  Swahili:
    'Asante kwa kutenga muda wa kukamilisha rekodi hii fupi ya sauti. Tafadhali soma aya ifuatayo kwa sauti, kwa uwazi, na kwa mwendo wa utulivu na wa kawaida, kama vile ungezungumza na mteja au mwenzako wa kazi katika siku ya kawaida ya kazi. Hakuna haja ya kuharakisha. Jambo muhimu zaidi ni kwamba maneno yako yaeleweke kwa urahisi na sauti yako isikike ikiwa na ujasiri, urafiki, na utulivu. Mawasiliano mazuri ni mojawapo ya stadi muhimu zaidi katika jukumu lolote. Inamaanisha kuzungumza kwa uwazi, kusikiliza kwa makini kile ambacho mtu mwingine anahitaji, na kujibu kwa subira na heshima. Tunapowasiliana vizuri, tunamsaidia kila mtu kuhisi amesikilizwa, amethaminiwa, na ameeleweka, hata wakati hali ni ngumu au jibu si lile alilotarajia. Sauti ya utulivu na ya kirafiki inaweza kubadilisha wakati wa kuchanganyikiwa kuwa uzoefu chanya. Kufanya kazi kama sehemu ya timu ya mbali pia kunahitaji umakini, uaminifu, na kutegemewa. Tunamwamini kila mwanachama wa timu yetu kusimamia vyema muda wake, kuwepo na kuwa tayari kwa kila zamu, na kuomba msaada wakati wowote anaohitaji. Makosa yatatokea mara kwa mara, na hilo ni jambo la kawaida kabisa. Kinachohesabika kweli ni jinsi tunavyojifunza kutokana nayo na kuendelea kuboresha pamoja. Unaposoma maneno haya, fikiria kwamba tayari wewe ni sehemu ya timu yetu, ukizungumza na mtu anayetegemea msaada wako. Vuta pumzi, legeza mabega yako, na iruhusu sauti yako ya asili itoke. Tunathamini kwa dhati juhudi unazofanya leo, na tunatazamia kujifunza zaidi kukuhusu. Asante tena, na bahati njema.',
  Ukrainian:
    'Дякуємо, що знайшли час зробити цей короткий голосовий запис. Будь ласка, прочитайте наведений нижче уривок уголос, чітко, у спокійному й природному темпі, так само, як ви говорили б із клієнтом чи колегою у звичайний робочий день. Поспішати не потрібно. Найважливіше — щоб ваші слова було легко зрозуміти, а голос звучав упевнено, привітно й спокійно. Хороше спілкування — одна з найважливіших навичок у будь-якій ролі. Воно означає говорити зрозуміло, уважно слухати те, що потрібно іншій людині, і відповідати терпляче й з повагою. Коли ми спілкуємося добре, ми допомагаємо кожній людині відчути, що її почули, оцінили й зрозуміли, навіть коли ситуація складна або відповідь не та, на яку вона сподівалася. Спокійний і привітний голос здатен перетворити неприємний момент на позитивний досвід. Робота у складі віддаленої команди також вимагає зосередженості, чесності й надійності. Ми довіряємо кожному учаснику нашої команди добре розпоряджатися своїм часом, бути присутнім і готовим до кожної зміни та звертатися по допомогу, коли це потрібно. Помилки час від часу трапляються, і це цілком нормально. По-справжньому важливо те, як ми вчимося на них і продовжуємо вдосконалюватися разом. Читаючи ці слова, уявіть, що ви вже частина нашої команди й розмовляєте з людиною, яка розраховує на вашу підтримку. Зробіть вдих, розслабте плечі й дозвольте звучати своєму природному голосу. Ми щиро цінуємо зусилля, які ви докладаєте сьогодні, і з нетерпінням чекаємо нагоди дізнатися більше про вас. Ще раз дякуємо і бажаємо успіху.',
  Afrikaans:
    "Dankie dat u die tyd geneem het om hierdie kort stemopname te voltooi. Lees asseblief die volgende paragraaf hardop, duidelik, teen 'n kalm en natuurlike pas, net soos u met 'n kliënt of kollega tydens 'n gewone werksdag sou praat. Daar is geen behoefte om te haas nie. Wat die belangrikste is, is dat u woorde maklik is om te verstaan en dat u selfversekerd, vriendelik en ontspanne klink. Goeie kommunikasie is een van die belangrikste vaardighede in enige rol. Dit beteken om duidelik te praat, aandagtig te luister na wat die ander persoon nodig het, en met geduld en respek te reageer. Wanneer ons goed kommunikeer, help ons elke persoon om gehoor, waardeer en verstaan te voel, selfs wanneer die situasie moeilik is of die antwoord nie is wat hulle gehoop het nie. 'n Kalm en vriendelike stem kan 'n frustrerende oomblik in 'n positiewe ervaring verander. Om as deel van 'n afgeleë span te werk, vereis ook fokus, eerlikheid en betroubaarheid. Ons vertrou elke lid van ons span om hul tyd goed te bestuur, teenwoordig en voorbereid te wees vir elke skof, en hulp te vra wanneer hulle dit nodig het. Foute sal van tyd tot tyd gebeur, en dit is heeltemal normaal. Wat werklik saak maak, is hoe ons daaruit leer en saam aanhou verbeter. Terwyl u hierdie woorde lees, verbeel u dat u reeds deel van ons span is en met iemand praat wat op u ondersteuning staatmaak. Haal asem, ontspan u skouers, en laat u natuurlike stem deurkom. Ons waardeer opreg die moeite wat u vandag doen, en ons sien daarna uit om meer van u te leer. Baie dankie weer, en sterkte.",
  Acholi:
    'Apwoyo pi miyo cawa me tyeko goyo dwon man machiek. Tim kica ikwan paragraph man maleng, ki dwon matek, ki i rwom ma kwaye ki ma obedo i yo me kwo, kit macalo iloko ki dano me cam onyo lawoti i nino me tic ma obedo. Pe mite me ringo. Gin maber loyo aye ni lok mamegi obed yot me niang ki dwoni obed ki gen, mar, ki kuc. Nyamo lok maber aye gin acel i kin lwak gin ma pire tek loyo i tic ducu. En te lokke ni lok maleng, winyo maber gin ma dano mukene mito, ki gamo ki diyo cwiny ki woro. Ka wanyamo lok maber, wakonyo dano ducu me winyo ni giwinyo gin, gimaro gin, ki gini ngeyo gin, kadi bed gin obedo tek onyo lagam pe obedo macalo gigeno. Dwon ma kuc ki ma maber twero loko cawa ma cwiny pe yom me obedo gin maber. Tic i kabedo me bedo i team ma bor bene mito tam, ada, ki gen. Wageno dano ducu i team me konyo cawa gi maber, me bedo tye ki yubbe pi cawa ducu me tic, ki me peny kony ka mite. Bal twero timme i kare mogo, ki man obedo gin ma kwo. Gin ma pire tek aye kit ma wapwonyo kwede ki me mede ki dongo kacel. Kun ikwano lok man, tam ni in dong ibedo dano me team-wa. Ywe yweny, kel cwinyi piny, ki we dwoni me kwo me wok woko. Wapwoyo matek miti ni tin, ki wamaro ngeyo madwong ikomi. Apwoyo doki, ki wamiyi gum.',
  Albanian:
    "Faleminderit që morët kohë për të përfunduar këtë regjistrim të shkurtër zanor. Ju lutemi lexoni paragrafin e mëposhtëm me zë të lartë, qartë, me një ritëm të qetë dhe natyral, ashtu siç do të flisnit me një klient ose koleg gjatë një dite normale pune. Nuk ka nevojë të nxitoni. Ajo që ka më shumë rëndësi është që fjalët tuaja të jenë të lehta për t'u kuptuar dhe që të tingëlloni të sigurt, miqësorë dhe të qetë. Komunikimi i mirë është një nga aftësitë më të rëndësishme në çdo rol. Ai do të thotë të flasësh qartë, të dëgjosh me kujdes atë që i nevojitet personit tjetër dhe të përgjigjesh me durim dhe respekt. Kur komunikojmë mirë, ndihmojmë çdo person të ndihet i dëgjuar, i vlerësuar dhe i kuptuar, edhe kur situata është e vështirë ose përgjigjja nuk është ajo që shpresonte. Një zë i qetë dhe miqësor mund ta kthejë një moment zhgënjyes në një përvojë pozitive. Të punosh si pjesë e një ekipi në distancë kërkon gjithashtu përqendrim, ndershmëri dhe besueshmëri. Ne i besojmë çdo anëtari të ekipit tonë që ta menaxhojë mirë kohën e tij, të jetë i pranishëm dhe i përgatitur për çdo turn dhe të kërkojë ndihmë sa herë që i nevojitet. Gabime do të ndodhin herë pas here, dhe kjo është krejtësisht normale. Ajo që ka vërtet rëndësi është se si mësojmë prej tyre dhe vazhdojmë të përmirësohemi së bashku. Ndërsa lexoni këto fjalë, imagjinoni se tashmë jeni pjesë e ekipit tonë, duke folur me dikë që mbështetet te ju. Merrni frymë, relaksoni shpatullat dhe lëreni zërin tuaj të natyrshëm të dalë. Ne e vlerësojmë sinqerisht përpjekjen që po bëni sot dhe presim me padurim t'ju njohim më shumë. Faleminderit përsëri dhe suksese.",
  ASL:
    'Thank you for taking the time to complete this short voice recording. Please read the following passage aloud clearly, at a calm and natural pace, just as you would speak with a customer or a colleague during a normal working day. There is no need to rush. What matters most is that your words are easy to understand and that you sound confident, friendly, and relaxed. Good communication is one of the most important skills in any role. It means speaking clearly, listening carefully to what the other person needs, and responding with patience and respect. When we communicate well, we help each person feel heard, valued, and understood, even when the situation is difficult or the answer is not the one they hoped to hear. A calm and friendly voice can turn a frustrating moment into a positive experience. Working as part of a remote team also requires focus, honesty, and reliability. We trust every member of our team to manage their time well, to be present and prepared for each shift, and to ask for help whenever they need it. Mistakes will happen from time to time, and that is completely normal. What truly counts is how we learn from them and keep improving together. As you read these words, imagine that you are already part of our team, speaking with someone who is depending on you for support. Take a breath, relax your shoulders, and let your natural voice come through. We genuinely appreciate the effort you are making today, and we look forward to learning more about you, your experience, and the strengths you would bring to our growing team. Thank you again, and good luck.',
  Azerbaijani:
    "Bu qısa səs yazısını tamamlamağa vaxt ayırdığınız üçün təşəkkür edirik. Zəhmət olmasa, aşağıdakı mətni ucadan, aydın şəkildə və sakit, təbii bir sürətlə oxuyun — adi bir iş günündə müştəri və ya həmkarınızla danışdığınız kimi. Tələsməyə ehtiyac yoxdur. Ən vacibi sözlərinizin asan anlaşılması və səsinizin özünə inamlı, mehriban və rahat səslənməsidir. Yaxşı ünsiyyət istənilən vəzifədə ən vacib bacarıqlardan biridir. Bu, aydın danışmaq, qarşı tərəfin nəyə ehtiyacı olduğunu diqqətlə dinləmək və səbir və hörmətlə cavab vermək deməkdir. Yaxşı ünsiyyət qurduqda, vəziyyət çətin olsa belə və ya cavab onların ümid etdiyi kimi olmasa belə, hər kəsin eşidildiyini, dəyər verildiyini və anlaşıldığını hiss etməsinə kömək edirik. Sakit və mehriban bir səs sıxıntılı bir anı müsbət bir təcrübəyə çevirə bilər. Uzaqdan komandanın bir hissəsi kimi işləmək həmçinin diqqət, dürüstlük və etibarlılıq tələb edir. Komandamızın hər bir üzvünün vaxtını yaxşı idarə edəcəyinə, hər növbəyə hazır olacağına və ehtiyac olduqda kömək istəyəcəyinə inanırıq. Səhvlər vaxtaşırı baş verəcək və bu tamamilə normaldır. Əsl vacib olan, onlardan necə dərs çıxarmağımız və birlikdə inkişaf etməyə davam etməyimizdir. Bu sözləri oxuyarkən, artıq komandamızın bir hissəsi olduğunuzu və dəstəyinizə güvənən biri ilə danışdığınızı təsəvvür edin. Nəfəs alın, çiyinlərinizi boşaldın və təbii səsinizin çıxmasına imkan verin. Bu gün göstərdiyiniz səyi səmimi qəlbdən qiymətləndiririk və sizi daha yaxından tanımağı səbirsizliklə gözləyirik. Bir daha təşəkkür edirik və uğurlar arzulayırıq.",
  Slovenian:
    'Hvala, ker ste si vzeli čas za ta kratki glasovni posnetek. Prosimo, da naslednji odstavek preberete na glas, razločno, v mirnem in naravnem tempu, tako kot bi se pogovarjali s stranko ali sodelavcem na običajen delovni dan. Ni se vam treba hiteti. Najpomembneje je, da so vaše besede lahko razumljive in da zvenite samozavestno, prijazno in sproščeno. Dobra komunikacija je ena najpomembnejših veščin v vsaki vlogi. Pomeni jasno govoriti, pozorno poslušati, kaj sogovornik potrebuje, ter odgovarjati potrpežljivo in spoštljivo. Ko se dobro sporazumevamo, vsaki osebi pomagamo, da se počuti slišano, cenjeno in razumljeno, tudi kadar je položaj težak ali odgovor ni tak, kot je upala. Miren in prijazen glas lahko spremeni neprijeten trenutek v pozitivno izkušnjo. Delo v oddaljeni ekipi zahteva tudi osredotočenost, poštenost in zanesljivost. Zaupamo, da vsak član naše ekipe dobro upravlja svoj čas, je prisoten in pripravljen na vsako izmeno ter prosi za pomoč, kadar jo potrebuje. Napake se občasno zgodijo, in to je povsem normalno. Resnično pomembno je, kako se iz njih učimo in skupaj napredujemo. Med branjem teh besed si predstavljajte, da ste že del naše ekipe in se pogovarjate z nekom, ki računa na vašo podporo. Vdihnite, sprostite ramena in pustite, da pride na dan vaš naravni glas. Iskreno cenimo trud, ki ga vlagate danes, in se veselimo, da vas bomo bolje spoznali. Še enkrat hvala in veliko sreče.',
  Somali:
    'Waad ku mahadsan tahay inaad waqti u qaadatay dhammaystirka duubistan codka ah ee gaaban. Fadlan si cad u akhri qoraalkan soo socda, adoo ku hadlaya xawaare degan oo dabiici ah, sida aad ula hadli lahayd macmiil ama saaxiibkaa shaqada maalin shaqo caadi ah. Uma baahnid inaad degdegto. Waxa ugu muhiimsan ayaa ah in erayadaadu si fudud loo fahmo iyo in codkaagu u dhawaaqo si kalsooni, saaxiibtinimo iyo degenaansho leh. Isgaarsiinta wanaagsan waa mid ka mid ah xirfadaha ugu muhiimsan doorka kasta. Waxay ka dhigan tahay inaad si cad u hadasho, aad si taxadar leh u dhegeysato waxa qofka kale u baahan yahay, oo aad ku jawaabto samir iyo ixtiraam. Markaan si fiican u isgaarsiino, waxaan ka caawinaa qof kasta inuu dareemo in la maqlay, la qiimeeyay, oo la fahmay, xataa marka xaaladdu adag tahay ama jawaabtu aysan ahayn tii uu rajaynayay. Cod degan oo saaxiibtinimo leh wuxuu u beddeli karaa daqiiqad niyad-jab ah waayo-aragnimo wanaagsan. Inaad ka shaqeyso koox fog ahaan waxay sidoo kale u baahan tahay diirad, daacadnimo, iyo lagu kalsoonaan karo. Waxaan ku kalsoonnahay xubin kasta oo kooxdayada ah inay si wanaagsan u maamusho waqtigeeda, ay joogto oo diyaar u tahay kala-goys kasta, oo ay caawimaad codsato mar kasta oo loo baahdo. Khaladaadku way dhici doonaan mar mar, taasna waa wax caadi ah. Waxa runtii muhiimka ah ayaa ah sida aan wax uga barano oo aan u sii horumarno wadajir. Inta aad akhrinayso ereyadan, qiyaaso inaad horeyba u tahay qayb ka mid ah kooxdayada, oo aad la hadlayso qof ku tiirsan taageeradaada. Neefso, dejisado garbahaaga, oo u oggolow codkaaga dabiiciga ah inuu soo baxo. Waxaan si dhab ah u qadarinaa dadaalka aad maanta gelayso, waxaana rajaynaynaa inaan wax badan kaa barano. Mar kale waad ku mahadsan tahay, nasiib wanaag.',
  Gujarati:
    'આ ટૂંકું વૉઇસ રેકોર્ડિંગ પૂર્ણ કરવા માટે સમય કાઢવા બદલ આપનો આભાર. કૃપા કરીને નીચેનો ફકરો સ્પષ્ટ રીતે, શાંત અને સ્વાભાવિક ગતિએ મોટેથી વાંચો, જેવી રીતે તમે કોઈ સામાન્ય કાર્યદિવસે ગ્રાહક અથવા સહકર્મી સાથે વાત કરો છો. ઉતાવળ કરવાની જરૂર નથી. સૌથી મહત્ત્વનું એ છે કે તમારા શબ્દો સમજવામાં સરળ હોય અને તમારો અવાજ આત્મવિશ્વાસપૂર્ણ, મૈત્રીપૂર્ણ અને હળવો લાગે. સારો સંચાર કોઈપણ ભૂમિકામાં સૌથી મહત્ત્વની કુશળતાઓમાંની એક છે. તેનો અર્થ છે સ્પષ્ટ રીતે બોલવું, સામેની વ્યક્તિને શું જોઈએ છે તે ધ્યાનથી સાંભળવું, અને ધીરજ અને આદર સાથે જવાબ આપવો. જ્યારે આપણે સારી રીતે સંચાર કરીએ છીએ, ત્યારે આપણે દરેક વ્યક્તિને એવો અનુભવ કરાવીએ છીએ કે તેની વાત સાંભળવામાં આવી, તેની કદર થઈ અને તેને સમજવામાં આવ્યો, ભલે પરિસ્થિતિ મુશ્કેલ હોય અથવા જવાબ તેણે આશા રાખી હતી તેવો ન હોય. એક શાંત અને મૈત્રીપૂર્ણ અવાજ નિરાશાજનક ક્ષણને હકારાત્મક અનુભવમાં બદલી શકે છે. દૂરસ્થ ટીમના ભાગ રૂપે કામ કરવા માટે એકાગ્રતા, પ્રામાણિકતા અને ભરોસાપાત્રતા પણ જરૂરી છે. અમને અમારી ટીમના દરેક સભ્ય પર વિશ્વાસ છે કે તે પોતાનો સમય સારી રીતે સંભાળશે, દરેક શિફ્ટ માટે હાજર અને તૈયાર રહેશે, અને જરૂર પડ્યે મદદ માગશે. ભૂલો ક્યારેક થતી રહે છે, અને તે સંપૂર્ણપણે સ્વાભાવિક છે. ખરેખર મહત્ત્વનું એ છે કે આપણે તેમાંથી કેવી રીતે શીખીએ છીએ અને સાથે મળીને સુધરતા રહીએ છીએ. આ શબ્દો વાંચતી વખતે કલ્પના કરો કે તમે પહેલેથી જ અમારી ટીમનો ભાગ છો. ઊંડો શ્વાસ લો, ખભા હળવા કરો, અને તમારા સ્વાભાવિક અવાજને બહાર આવવા દો. આજે તમે કરી રહેલા પ્રયત્નની અમે દિલથી કદર કરીએ છીએ અને તમારા વિશે વધુ જાણવા આતુર છીએ. ફરી એકવાર આભાર અને શુભકામનાઓ.',
  'Haitian Creole':
    "Mèsi paske ou pran tan pou w fè ti anrejistreman vwa kout sa a. Tanpri li paragraf ki anba a awotvwa, klèman, nan yon vitès kalm e natirèl, menm jan ou ta pale ak yon kliyan oswa yon kòlèg pandan yon jounen travay nòmal. Pa gen bezwen prese. Sa ki pi enpòtan se pou pawòl ou yo fasil pou konprann epi pou vwa ou sonnen ak konfyans, zanmitay, e detann. Bon kominikasyon se youn nan konpetans ki pi enpòtan nan nenpòt wòl. Li vle di pale klè, koute ak atansyon sa lòt moun nan bezwen, epi reponn ak pasyans e respè. Lè nou kominike byen, nou ede chak moun santi yo tande, valorize, e konprann, menm lè sitiyasyon an difisil oswa repons lan se pa sa yo te espere. Yon vwa kalm e zanmitay kapab chanje yon moman fristran an yon eksperyans pozitif. Travay kòm yon pati nan yon ekip a distans mande tou konsantrasyon, onètete, ak fyabilite. Nou fè konfyans chak manm ekip nou an pou jere tan yo byen, pou yo prezan e pare pou chak èkip, epi pou yo mande èd chak fwa yo bezwen li. Erè ap rive detanzantan, e sa nòmal nèt. Sa ki vrèman konte se kijan nou aprann nan yo epi kontinye amelyore ansanm. Pandan w ap li mo sa yo, imajine ou deja yon pati nan ekip nou an, ap pale ak yon moun ki konte sou sipò ou. Pran yon souf, detann zepòl ou, epi kite vwa natirèl ou soti. Nou sensèman apresye efò w ap fè jodi a, epi nou gen anvi konnen plis sou ou. Mèsi ankò, epi bòn chans.",
  Hmong:
    'Ua tsaug rau koj lub sijhawm los ua qhov kev kaw suab luv luv no. Thov nyeem nqe lus hauv qab no nrov nrov, kom meej, ntawm tus nqi maj mam thiab raws li koj lub suab niaj hnub, ib yam li koj txoj kev hais lus rau ib tug neeg yuav khoom los yog ib tug npoj tsev hauj lwm hauv ib hnub ua hauj lwm. Tsis tas yuav maj. Qhov tseem ceeb tshaj plaws yog kom koj cov lus yooj yim nkag siab thiab koj lub suab muaj kev ntseeg siab, phooj ywg, thiab so. Kev sib txuas lus zoo yog ib qho kev txawj ntse tseem ceeb tshaj plaws hauv txhua txoj hauj lwm. Nws txhais tau tias hais lus meej, mloog zoo li lwm tus xav tau, thiab teb nrog kev ua siab ntev thiab kev hwm. Thaum peb sib txuas lus zoo, peb pab txhua tus kom hnov tias luag hnov lawv, luag saib taus lawv, thiab luag nkag siab lawv, txawm tias qhov xwm txheej nyuaj los yog cov lus teb tsis yog qhov lawv cia siab. Ib lub suab nyob tus yees thiab ua phooj ywg tuaj yeem hloov ib lub sijhawm chim siab los ua ib qho kev paub zoo. Kev ua hauj lwm raws li ib feem ntawm ib pawg nyob deb kuj xav tau kev mob siab, kev ncaj ncees, thiab kev tso siab tau. Peb ntseeg siab txhua tus tswv cuab hauv peb pab pawg los tswj lawv lub sijhawm zoo, nyob ntawm no thiab npaj txhij rau txhua qhov hloov, thiab thov kev pab thaum twg lawv xav tau. Cov kev ua yuam kev yuav tshwm sim ib ntus, thiab qhov no yog ib qho kev xwm txheej. Qhov tseem ceeb tiag tiag yog peb kawm li cas los ntawm lawv thiab txuas ntxiv ua kom zoo dua ua ke. Thaum koj nyeem cov lus no, xav txog tias koj twb yog ib feem ntawm peb pab pawg lawm. Ua pa, so koj lub xub pwg, thiab cia koj lub suab niaj hnub tawm los. Peb ua tsaug rau koj txoj kev siv zog hnub no, thiab peb cia siab tias yuav paub ntau ntxiv txog koj. Ua tsaug dua ib zaug ntxiv, thiab thov kom koj muaj hmoov zoo.',
  Laotian:
    'ຂໍຂອບໃຈທີ່ສະຫຼະເວລາເພື່ອເຮັດການບັນທຶກສຽງສັ້ນໆນີ້. ກະລຸນາອ່ານວັກຕໍ່ໄປນີ້ດ້ວຍສຽງດັງ, ໃຫ້ຊັດເຈນ, ດ້ວຍຈັງຫວະທີ່ສະຫງົບແລະເປັນທຳມະຊາດ, ຄືກັບທີ່ທ່ານເວົ້າກັບລູກຄ້າຫຼືເພື່ອນຮ່ວມງານໃນມື້ເຮັດວຽກປົກກະຕິ. ບໍ່ຈຳເປັນຕ້ອງຟ້າວ. ສິ່ງທີ່ສຳຄັນທີ່ສຸດແມ່ນຄຳເວົ້າຂອງທ່ານເຂົ້າໃຈໄດ້ງ່າຍ ແລະ ສຽງຂອງທ່ານຟັງແລ້ວໝັ້ນໃຈ, ເປັນມິດ ແລະ ຜ່ອນຄາຍ. ການສື່ສານທີ່ດີແມ່ນໜຶ່ງໃນທັກສະທີ່ສຳຄັນທີ່ສຸດໃນທຸກໜ້າທີ່. ມັນໝາຍເຖິງການເວົ້າຢ່າງຊັດເຈນ, ການຟັງຢ່າງຕັ້ງໃຈວ່າອີກຝ່າຍຕ້ອງການຫຍັງ, ແລະ ການຕອບດ້ວຍຄວາມອົດທົນແລະຄວາມເຄົາລົບ. ເມື່ອພວກເຮົາສື່ສານໄດ້ດີ, ພວກເຮົາຊ່ວຍໃຫ້ແຕ່ລະຄົນຮູ້ສຶກວ່າຖືກຮັບຟັງ, ມີຄຸນຄ່າ ແລະ ເຂົ້າໃຈ, ເຖິງແມ່ນວ່າສະຖານະການຈະຫຍຸ້ງຍາກ ຫຼື ຄຳຕອບຈະບໍ່ເປັນຢ່າງທີ່ເຂົາຫວັງ. ສຽງທີ່ສະຫງົບແລະເປັນມິດສາມາດປ່ຽນຊ່ວງເວລາທີ່ໜ້າຜິດຫວັງໃຫ້ກາຍເປັນປະສົບການທີ່ດີໄດ້. ການເຮັດວຽກເປັນສ່ວນໜຶ່ງຂອງທີມງານທາງໄກຍັງຕ້ອງການຄວາມຕັ້ງໃຈ, ຄວາມຊື່ສັດ ແລະ ຄວາມໜ້າເຊື່ອຖື. ພວກເຮົາໄວ້ໃຈສະມາຊິກທຸກຄົນໃນທີມງານໃຫ້ຄຸ້ມຄອງເວລາຂອງຕົນໄດ້ດີ, ມີຢູ່ ແລະ ກຽມພ້ອມສຳລັບທຸກກະ, ແລະ ຂໍຄວາມຊ່ວຍເຫຼືອເມື່ອໃດກໍຕາມທີ່ຕ້ອງການ. ຄວາມຜິດພາດຈະເກີດຂຶ້ນເປັນບາງຄັ້ງ, ແລະ ນັ້ນເປັນເລື່ອງປົກກະຕິຢ່າງສິ້ນເຊີງ. ສິ່ງທີ່ສຳຄັນແທ້ໆແມ່ນວິທີທີ່ພວກເຮົາຮຽນຮູ້ຈາກມັນ ແລະ ສືບຕໍ່ພັດທະນາຮ່ວມກັນ. ໃນຂະນະທີ່ທ່ານອ່ານຄຳເຫຼົ່ານີ້, ຈິນຕະນາການວ່າທ່ານເປັນສ່ວນໜຶ່ງຂອງທີມງານພວກເຮົາແລ້ວ. ຫາຍໃຈເຂົ້າ, ຜ່ອນຄາຍບ່າຂອງທ່ານ, ແລະ ປ່ອຍໃຫ້ສຽງທຳມະຊາດຂອງທ່ານອອກມາ. ພວກເຮົາຮູ້ບຸນຄຸນຢ່າງຈິງໃຈຕໍ່ຄວາມພະຍາຍາມຂອງທ່ານໃນມື້ນີ້, ແລະ ຫວັງວ່າຈະໄດ້ຮູ້ຈັກທ່ານຫຼາຍຂຶ້ນ. ຂອບໃຈອີກຄັ້ງ ແລະ ຂໍໃຫ້ໂຊກດີ.',
  Lingala:
    'Matondi mpo na kozwa ntango ya kosala enregistrement oyo ya mokuse ya mongongo. Tobondeli yo, tanga paragraphe oyo na nse na mongongo makasi, na bopɛto, na rythme ya kimia mpe ya bomoto, ndenge okoloba na kiliya to na moninga ya mosala na mokolo ya mosala ya momeseno. Esengeli te kowela. Likambo ya ntina mingi ezali ete maloba na yo ezala pɛto mpo na kososola, mpe mongongo na yo eyoka na elikya, na boninga, mpe na kimia. Communication ya malamu ezali moko ya mayele ya ntina mingi na mosala nyonso. Yango elimboli koloba polele, koyoka na bokɛngi nini moto mosusu azali na yango mposa, mpe kozongisa na motema molai mpe limemia. Tango tozali kosolola malamu, tosalisaka moto nyonso ayoka ete bayoki ye, batali ye motuya, mpe basosoli ye, ata soki likambo ezali mpasi to eyano ezali te oyo azalaki kozela. Mongongo ya kimia mpe ya boninga ekoki kobongola ntango ya mawa kokóma experience ya malamu. Kosala lokola eteni ya ekipi ya mosika esengaka mpe likebi, bosembo, mpe komipesa. Tozali kotyela moto nyonso ya ekipi na biso motema ete asala na ntango na ye malamu, azala mpe amibongisa mpo na shift nyonso, mpe asɛnga lisalisi tango nyonso azali na yango mposa. Mabunga ekoya tango na tango, mpe yango ezali likambo ya momeseno mpenza. Likambo ya solo ya ntina ezali ndenge nini tozali koyekola na yango mpe kokoba kobongisa elongo. Wana ozali kotanga maloba oyo, kanisa ete osili kozala eteni ya ekipi na biso, ozali kosolola na moto oyo azali kotyela yo motema mpo na lisungi. Pema, lɛmbisa mapeka na yo, mpe tika mongongo na yo ya bomoto ebima. Tozali na botondi ya solo mpo na milende oyo ozali kosala lelo, mpe tozali kozela koyeba makambo mingi na ntina na yo. Matondi lisusu, mpe tika ozala na chance.',
  Marshallese:
    "Kom̧m̧ool kōn am̧ bōk iien ñan kadedeikļo̧k recording in ekadu. Joij im riiti pforce in ilo ainikien eļap, alikkar, im ilo juon mōkaj eaenōm̧m̧an im ejim̧we, āinwōt am̧ naaj kōnono ippān juon rituinwōt ak juon rijerbal m̧ōttam̧ ilo juon raan in jerbal ejjeļo̧k oktak. Ejjeļo̧k unin am̧ kaiur. Men eo eaorōktata ej bwe naan ko am̧ ren pidodo ñan meļeļe im bwe ainikiōm̧ en jejjet, jouj, im aenōm̧m̧an. Kōnono em̧m̧an ej juon iaan kapeel ko reaorōktata ilo jabdewōt jerbal. Ej meļeļein kōnono alikkar, roñjake eļap ta eo armej eo juon ej aikuji, im uwaak kōn meanwōd im kautiej. Ñe jej kōnono em̧m̧an, jej jipañ armej otemjej bwe ren eñjake bwe rej roñ er, kaorōk er, im meļeļe er, meñe wāween eo epen ak uwaak eo ejjab men eo raar kōjatdikdik kake. Juon ainikien eaenōm̧m̧an im jouj emaroñ ukōt juon iien einnaan ñan juon eñjake em̧m̧an. Jerbal āinwōt m̧ōttan juon kumi ettoļo̧k ej bar aikuji ļōmņak, m̧ool, im liāp. Jej liāpe kajjojo ri-kumi in am ñan kōm̧m̧an iien eo aer em̧m̧an, pād im pojak ñan kajjojo shift, im kajjitōk jipañ jabdewōt iien rej aikuji. Bōd ko renaaj waļo̧k jet iien, im men in ej men eo ekkar. Men eo em̧ool eaorōk ej wāween ad katak jān er im wōnm̧aanļo̧k im kōkōm̧anm̧anļo̧k ippān doon. Ilo am̧ riiti naan kein, ļōmņak bwe kwōj m̧ōttan kumi in am, kōnono ippān juon eo ej lōke eok kōn jipañ. Em̧m̧en, kōm̧m̧an bwe aeran en aenōm̧m̧an, im kōtļo̧k ainikiōm̧ eaorōk en waļo̧k. Kōmij kanooj kam̧m̧oolol kijejeto eo kwōj kōm̧m̧ane rainin, im kōmij kōttar ñan jeļā eļapļo̧k kōn kwe. Kom̧m̧ool bar juon alen, im jeraam̧m̧an.",
  Pashto:
    'مننه چې د دې لنډ غږیز ثبت بشپړولو لپاره مو وخت راوویست. مهرباني وکړئ لاندې پراګراف په لوړ غږ، روښانه ډول، او په آرام او طبیعي سرعت سره ولولئ، لکه څنګه چې تاسو د یوې عادي کاري ورځې په جریان کې له پیرودونکي یا همکار سره خبرې کوئ. بیړې ته اړتیا نشته. تر ټولو مهمه دا ده چې ستاسو کلمې د پوهیدو لپاره اسانه وي او ستاسو غږ باوري، دوستانه او آرام واوریدل شي. ښه اړیکه په هر رول کې یوه له خورا مهمو مهارتونو څخه ده. دا پدې مانا ده چې په روښانه توګه خبرې کول، په پاملرنې سره اوریدل چې بل کس څه ته اړتیا لري، او په صبر او درناوي سره ځواب ورکول. کله چې موږ ښه اړیکه ونیسو، موږ هر کس سره مرسته کوو چې احساس وکړي چې د هغه خبره اوریدل شوې، قدر یې شوی او پوه یې شوي، حتی کله چې حالت ستونزمن وي یا ځواب هغه نه وي چې هغه یې تمه درلوده. یو آرام او دوستانه غږ کولی شي یوه خپه کوونکې شیبه په مثبته تجربه بدله کړي. د لرې پرتو ډلې د یوې برخې په توګه کار کول هم تمرکز، صداقت او د باور وړ والی ته اړتیا لري. موږ زموږ د ډلې پر هر غړي باور لرو چې د خپل وخت ښه مدیریت وکړي، د هرې وزمې لپاره حاضر او چمتو وي، او کله چې اړتیا وي مرسته وغواړي. تېروتنې به وخت په وخت پیښیږي، او دا بشپړ طبیعي خبره ده. هغه څه چې واقعیا مهم دي دا دي چې موږ څنګه له هغوی څخه زده کوو او یوځای ښه کیدو ته دوام ورکوو. د دې کلماتو لوستلو پر مهال تصور وکړئ چې تاسو لا دمخه زموږ د ډلې برخه یاست. یو ژور ساه واخلئ، خپلې اوږې آرامې کړئ، او خپل طبیعي غږ ته اجازه ورکړئ چې راڅرګند شي. موږ نن ستاسو هڅې له زړه څخه قدروو او ستاسو په اړه د نورو معلوماتو زده کولو ته سترګې په لار یو. یو ځل بیا مننه او بریا مو غواړو.',
  Rohingya:
    'Shukuria tuáñre yián chooto voice record goribar otté shomói diyé deér lái. Meérbani gorí yián fíchu or paragraph ókkol forishkar gorí, aram ar tabi’i gotité, zoré forí — zendilla tuñí ekkán aam kaam or din ot grahok yáto saáti loi maat gorí. Joldi goribar dorkar nái. Hosbbot asol baat ye hoói de tuáñr maat ókkol bujibellá ašan óibo ar tuáñr awaz e atmobishash, dustí ar aram loi súnae. Bála communication ye fottí kaam ot hubbout zoroori kúshi ókkol or ekkán. Iyán or maani oilo forishkar gorí maat hoón, dúsra zonor dorkar híyalé súnon, ar šobor ar izzot loi jowab diyón. Zehón añra bála gorí maat gorí, añra fottí zonore yián feel goráiyi de tuáñr maat súníye, izzot diíye, ar bujíye, hárr halote oilébi yáto jowab tuáñr ašaa hisabe nóóilébi. Ekkán aram ar dustí awaz e ekkán dukhór muhúrtore ekkán bála experience banai félaibou. Door or ekkán team or hisse hisabe kaam goróon e mongojo, sotti, ar bishash zogai. Añra fottí team member ore bishash gorí de tundé nizor shomói bála gorí solaibou, fottí shift otté házir ar toiyar tákibou, ar zehón dorkar tehón modot saibou. Bul ókkol kun kun shomói óibou, ar yián ekdom tabi’i baat. Asol baat oilo añra hetundé hibttu hibttu šikí ar eklla mili bála óite tákí. Ye lafz ókkol forí yian or shomói, soóch gorí lo tuñí agottottu añr team or hisse oyi giyó. Ekkán dom lo, tuáñr kandó aram goró, ar tuáñr tabi’i awaz ore beraibellá diyó. Añra tuáñr aijja or mehnotore háñçça gorí izzot gorí, ar tuáñr híyalé arde zanibellá aša gorí. Aro ekbar shukuria, ar Allah tuáñre bála rakké.',
};

const TOPIC =
  'your most recent work experience, your key responsibilities, and why you are a strong candidate for this role';

export interface ReadingTask {
  mode: 'read' | 'speak';
  language: string;
  passage: string;   // text to read, or the topic prompt for free speech
  instruction: string;
}

// Resolve the reading task for a given language. If we have a curated passage,
// the candidate reads it; otherwise they speak freely in that language.
export function getReadingTask(language?: string | null): ReadingTask {
  const lang = (language || 'English').trim();
  const passage = READING_PASSAGES[lang];
  if (passage) {
    return {
      mode: 'read',
      language: lang,
      passage,
      instruction: `Please read the passage below aloud in ${lang}, clearly and at a natural pace. You don't need to finish the whole passage — keep reading for at least 15 seconds.`,
    };
  }
  return {
    mode: 'speak',
    language: lang,
    passage: TOPIC,
    instruction: `Please speak in ${lang} for at least 15 seconds about ${TOPIC}. Speak naturally and clearly.`,
  };
}
